### ISSUE TITLE
SBT support

### ISSUE THREAD

**Issue by mb720** [wheaties/Predicates#2]
Hi wheaties!

Thank you very much for your library!

I'd like to use it in my sbt project; Is there a way I can do that à la: 
`libraryDependencies += "com.wheaties" %% "scala-predicates" % "1.0"`

Thanks in advance!
Matthias

**Comment by wheaties** [comment]
I never actually got it publishing. In reality, I should revisit it and make it "better" but for some reason each time I try to do it, I'm not happy with the result. Pull requests welcome.

**Comment by mb720** [comment]
Perfection is the enemy of the good, I'd say.
The library will definitely get more pull requests if you'd publish it because it's easier to use that way.

**Comment by wheaties** [comment]
How right you are. Ok, I want to remove those "Choices" thing I was working on. Now that I have a more developed concept of a few things, I find that much of what I was trying to do is flawed. The rest could stay.

**Comment by wheaties** [comment]
Opened a ticket to finally get this up somewhere where it can be used:

https://issues.sonatype.org/browse/OSSRH-16061

**Comment by wheaties** [comment]
Alright, I've staged the deploy. Soon will have an initial release.

**Comment by wheaties** [comment]
Should be able to download using

``` scala
libraryDependencies += "com.github.wheaties" %% "predicates" % "0.1"
```

**Comment by wheaties** [comment]
See: https://oss.sonatype.org/content/repositories/releases/com/github/wheaties/predicates_2.11/

**Comment by mb720** [comment]
Great! :-) Thank you.
